const fonts = {
    thin: 'SF Pro Display Thin',
    ultralight: 'SF Pro Display Ultralight',
    light: 'SF Pro Display Light',
    heavy: 'SF Pro Display Heavy',
    black: 'SF Pro Display Black',
    regular: 'SF Pro',
    system: 'SF Pro',
    rounded: 'SF Pro',
    medium: 'SF Pro',
    bold: 'SF Pro',
    timestamp: 'System',
    italic: 'SF Pro Display Regular Italic',
    bolditalic: 'SF Pro Display Bold Italic',
    semibold: 'SF Pro Display Semibold',
    mono: 'iAWriterMonoS-Regular',
    monoItalic: 'iAWriterMonoS-Italic',
    monoBold: 'iAWriterMonoS-Bold',
    monoBoldItalic: 'iAWriterMonoS-BoldItalic',
}; //AvenirNext / SanFrancisco Pro display set

// const fonts = {
//     thin: 'SF Pro Display Thin',
//     ultralight: 'SF Pro Display Ultralight',
//     light: 'SF Pro Display Light',
//     heavy: 'SF Pro Display Heavy',
//     black: 'SF Pro Display Black',
//     regular: 'SF Pro',
//     system: 'SF Pro',
//     rounded: 'SF Pro',
//     medium: 'SF Pro',
//     bold: 'SF Pro',
//     timestamp: 'AvenirNextLTPro-Regular',
//     italic: 'SF Pro Display Italic',
//     bolditalic: 'SF Pro Display Bold Italic',
//     semibold: 'SF Pro Display Semibold',
//     mono: 'iAWriterMonoS-Regular',
//     monoItalic: 'iAWriterMonoS-Italic',
//     monoBold: 'iAWriterMonoS-Bold',
//     monoBoldItalic: 'iAWriterMonoS-BoldItalic',
// }; //AvenirNext / SanFrancisco Pro display set

// const fonts = {
//     thin: 'System',
//     ultralight: 'System',
//     light: 'System',
//     heavy: 'System',
//     black: 'System',
//     regular: 'System',
//     system: 'System',
//     rounded: 'System',
//     medium: 'System',
//     bold: 'System',
//     timestamp: 'AvenirNextLTPro-Regular',
//     italic: 'System',
//     bolditalic: 'System',
//     semibold: 'System',
//     mono: 'iAWriterMonoS-Regular',
//     monoItalic: 'iAWriterMonoS-Italic',
//     monoBold: 'iAWriterMonoS-Bold',
//     monoBoldItalic: 'iAWriterMonoS-BoldItalic',
// }; //AvenirNext / SanFrancisco Pro display set

/*const fonts = {
    thin: 'SF-Pro-Rounded-Thin',
    ultralight: 'SF-Pro-Rounded-Ultralight',
    light: 'SF-Pro-Rounded-Light',
    regular: 'SF-Pro-Rounded-Regular',
    medium: 'SF-Pro-Rounded-Medium',
    heavy: 'SF-Pro-Rounded-Heavy',
    black: 'SF-Pro-Rounded-Black',
    bold: 'SF-Pro-Rounded-Bold',
    semibold: 'SF-Pro-Rounded-Semibold',
    mono: 'iAWriterMonoS-Regular',
    monoItalic: 'iAWriterMonoS-Italic',
    monoBold: 'iAWriterMonoS-Bold',
    monoBoldItalic: 'iAWriterMonoS-BoldItalic',
}; //SanFrancisco Pro Rounded set*/

export default fonts;
