import {StyleSheet, Platform} from 'react-native';
import colors from 'resources/colors';
import fonts from 'resources/fonts';
import baseText from 'resources/text';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'column',
        borderColor: '#1B1D1F',
        borderWidth: 2,
        borderRadius: 2,
        marginLeft: 5,
        marginRight: 5,
        marginTop: 5,
        marginBottom: 5,
        paddingLeft: 16,
        paddingRight: 16,
        backgroundColor: '#1B1D1F',
    },
    reportModalContainer: {
        borderWidth: 0,
        borderColor: 'orange',
        flexDirection: 'row',
    },
    userInfoContainer: {
        flexDirection: 'row',
        marginTop: 0,
        borderColor: 'red',
        borderWidth: 5,
        flex: 1,
        display: 'none',
    },
    postContainer: {
        flex: 1,
        borderColor: 'yellow',
        borderWidth: 0,
        marginTop: 12,
        marginBottom: 12,
        flexDirection: 'row',
    },
    postSubContainer: {
        flex: 1,
        borderWidth: 0,
        borderColor: 'purple',
        justifyContent: 'center',
    },
    postTitle: {
        marginRight: 20,
        fontSize: 18,
        fontWeight: '500',
        color: '#D0D3D6',
        flex: 1,
    },
    postDetailContainer: {
        borderWidth: 0,
        borderColor: 'red',
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    pinPostButton: {
        borderWidth: 0,
        borderColor: 'green',
        marginLeft: 0,
    },
    editPostButton: {
        borderWidth: 0,
        marginLeft: 10,
    },
    bookMarkPostButton: {
        borderWidth: 0,
        marginLeft: 10,
        marginRight: 15,
    },
    remixPostPreviewContainer: {
        marginLeft: 10,
        marginRight: 10,
        marginTop: -12,
        marginBottom: 6,
    },
    artistContainer: {
        width: '100%',
        borderColor: 'yellow',
        marginBottom: 15,
        borderWidth: 0,
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
    },
    artistSubContainer: largeWidth => ({
        position: 'absolute',
        top: 0,
        width: largeWidth - 15,
        height: largeWidth - 15,
        borderRadius: largeWidth,
        borderWidth: 1.5,
        borderColor: colors.seperatorLineColor,
        backgroundColor: colors.homeBackground,
    }),
    artistImage: (largeWidth, artistPersonaName) => ({
        width: largeWidth - 15,
        height: largeWidth - 15,
        borderRadius: largeWidth,
        borderWidth: 1.5,
        borderColor: colors.timeline,
        opacity: artistPersonaName !== '' ? 1 : 0.5,
    }),
    artistText: artistPersonaName => ({
        ...baseText,
        marginTop: 10,
        fontFamily: fonts.medium,
        color: artistPersonaName !== '' ? colors.text : colors.textFaded2,
        fontSize: 18,
        opacity: artistPersonaName !== '' ? 1 : 0.7,
    }),
    postMedia: maxHeight => ({
        borderRadius: 0,
        maxHeight: maxHeight,
        maxWidth: Platform.OS === 'ios' ? '93%' : '100%', // TODO (William) : for the FORUM post image center
        right: Platform.OS === 'ios' ? 3 : 0, // TODO (William) : for the FORUM post image center
        zIndex: 100000,
        elevation: 100000,
        borderColor: 'blue',
        borderWidth: 0,
        flex: 0,
    }),
    postMediaContainer: {
        borderWidth: 0,
        borderColor: '#444',
        borderRadius: 0,
        flex: 1,
        marginBottom: 15,
    },
    userNameContainer: {
        borderColor: 'green',
        flex: 1,
        borderWidth: 5, //0.4,
        flexDirection: 'row',
        marginBottom: 0,
        padding: 0,
    },
    userNameText: {
        padding: 0,
        ...baseText,
        lineHeight: null,
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        color: colors.text,
        fontFamily: fonts.medium,
        fontSize: 18,
        marginStart: -2,
        flex: 2,
        borderColor: 'blue',
        borderWidth: 5,
    },
    timeStampText: {
        ...baseText,
        flex: 0,
        marginStart: 4,
        justifyContent: 'center',
        alignSelf: 'center',
        alignItems: 'center',
        color: colors.textFaded2,
        fontSize: 12,
        fontFamily: fonts.timestamp,
        top: 0,
    },
});

export default styles;
