import {Dimensions, StyleSheet} from 'react-native';
import {useBatteryLevel} from 'react-native-device-info';
import {colors, palette} from 'resources';

const styles = StyleSheet.create({
    blackboardButton: {
        borderWidth: 1,
        borderColor: colors.maxFaded,
        padding: 7,
        borderRadius: 25,
    },
    blackboardButtonText: {
        fontSize: 14,
        color: colors.text,
    },
    promiseContainer: {
        position: 'absolute',
        left: 27,
        top: 7,
    },
    promiseEndUp: {
        ...palette.timeline.line,
        borderLeftWidth: 2,
        borderBottomWidth: 2,
        borderBottomLeftRadius: 13,
        borderBottomColor: colors.timeline,
        borderLeftColor: colors.timeline,
        width: 30,
        marginLeft: 4,
        marginTop: 29.5,
        position: 'absolute',
        height: 23,
        backgroundColor: undefined,
    },
    promiseText: {
        marginStart: 21,
        paddingRight: 10,
        color: colors.textFaded2,
        fontWeight: 'bold',
        fontSize: 14,
        marginTop: 4,
        marginRight: 4,
    },
    promiseUp: {
        position: 'absolute',
        marginLeft: 1,
        marginTop: 22.5,
        width: 8,
        height: 8,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: colors.timeline,
    },
    promiseEndDown: {
        ...palette.timeline.line,
        borderLeftWidth: 2,
        borderTopWidth: 2,
        borderTopLeftRadius: 13,
        borderTopColor: colors.timeline,
        borderLeftColor: colors.timeline,
        width: 30,
        marginLeft: 4,
        marginTop: 49.5,
        position: 'absolute',
        height: 23,
        backgroundColor: undefined,
    },
    promiseDown: {
        position: 'absolute',
        marginLeft: 1,
        marginTop: 70.5,
        width: 8,
        height: 8,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: colors.timeline,
        backgroundColor: colors.timeline,
    },
    artistTimeline: {
        ...palette.timeline.line,
        position: 'absolute',
        top: -5,
        width: 2,
        height: 70,
        left: -64,
        marginTop: -11.5,
        zIndex: 4,
    },
    artistPost: {
        flex: 1,
        paddingRight: 15,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.timeline,
        marginRight: 22,
        marginLeft: 33,
        marginTop: 10,
        paddingLeft: -20,
        marginBottom: 15,
        backgroundColor: colors.homeBackground,
    },
    post: {
        backgroundColor: '#181D1F',
        marginStart: 20,
        marginEnd: 20,
        // marginTop: 20,
        borderRadius: 8,
    },
    showcasePost: {
        paddingTop: 20,
        paddingBottom: 20,
        width: Dimensions.get('window').width - 2.5,
    },
    upperTimeline: {
        ...palette.timeline.line,
        marginLeft:
            palette.timeline.line.marginLeft -
            palette.post.marginLeft -
            palette.post.borderLeftWidth +
            1,
        position: 'absolute',
        height: 75,
        backgroundColor: colors.timeline,
    },
    lowerTimeline: {
        borderTopRightRadius: 5,
        borderTopLeftRadius: 5,
        ...palette.timeline.line,
        marginLeft:
            palette.timeline.line.marginLeft -
            palette.post.marginLeft -
            palette.post.borderLeftWidth +
            1,
        position: 'absolute',
        bottom: -1,
        backgroundColor: colors.timeline,
    },
    expandButton: {
        opacity: 1,
        position: 'absolute',
        backgroundColor: '#737373',
        width: 16,
        height: 16,
        left: 28,
        bottom: 1,
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        zIndex: 3000,
        shadowOpacity: 0.23,
        shadowRadius: 2.62,
        elevation: 4,
    },
    contractedSeperator: {
        marginLeft: 10,
        marginRight: 10,
        borderBottomWidth: 1,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        height: 20,
        width: '95%',
        position: 'absolute',
        zIndex: 100,
        borderBottomColor: colors.seperatorLineColor,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
    },
    endorsementsContainer: {
        flexDirection: 'row',
        marginLeft: 10,
    },
    endorsementBtn: {
        marginLeft: 7,
        marginRight: 7,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.topBackground,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        opacity: 1,
        shadowOpacity: 0.23,
        shadowRadius: 1,
        height: 42,
        width: 42,
        borderRadius: 40,
    },
    endorsementsMenuIos: {
        alignSelf: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        height: 60,
        paddingLeft: 5,
        paddingRight: 6,
        borderRadius: 30,
    },
    endorsementsMenuAndroid: {
        alignSelf: 'center',
        top: 200,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        elevation: 6,
        height: 60,
        paddingLeft: 5,
        paddingRight: 6,
        borderRadius: 30,
        backgroundColor: '#919191',
        opacity: 0.8,
    },
    commentEndorsements: {
        marginLeft: 3,
        marginRight: 3,
        borderWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 25,
        paddingLeft: 5,
        paddingRight: 7,
        width: 50,
        borderRadius: 40,
        marginTop: 2,
        marginBottom: 4,
    },
    threadBreakoutStyle: {
        marginLeft: palette.timeline.line.marginLeft - 5,
        width: 30,
        height: 30,
        zIndex: 0,
        marginTop: 7,
        borderBottomLeftRadius: 15,
        borderLeftWidth: 2,
        borderBottomWidth: 1.5,
        borderLeftColor: colors.timeline,
        borderBottomColor: colors.timeline,
        position: 'absolute',
    },
    threadTextBox: {
        marginLeft: 46,
        marginRight: 20,
        fontSize: 14,
        borderRadius: 5,
        borderWidth: 0.5,
        borderColor: colors.darkSeperator,
        paddingLeft: 8,
        paddingRight: 9,
        paddingBottom: 7,
        paddingTop: 4,
        marginBottom: 0,
        marginTop: 3,
        backgroundColor: colors.homeBackground,
    },
    text: {
        color: colors.text,
        marginLeft: 10,
        marginRight: 10,
        fontSize: 14,
    },
    replyText: {
        color: colors.textFaded2,
        fontSize: 14,
        fontStyle: 'italic',
        paddingLeft: 17.5,
    },
    replyHeaderText: {
        color: colors.textFaded2,
        fontSize: 14,
    },
    replyTextHeader: {
        height: 13,
        marginTop: 3,
        marginBottom: 4,
        flexDirection: 'row',
    },
    infoContainer: {
        flexDirection: 'column',
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        flex: 1,
    },
    personName: {
        color: colors.text,
        fontSize: 14,
        marginStart: 10,
        fontWeight: 'bold',
    },
    tinyPersonImage: {
        width: 13,
        height: 13,
        borderRadius: 13,
        marginRight: 4,
        opacity: 0.75,
    },
    threadBoxInfo: {
        marginLeft: 0,
        fontSize: 14,
        color: colors.textFaded2,
        marginTop: 2,
        marginBottom: 0,
        height: 20,
    },
    artistPostBreakout: {
        position: 'absolute',
        marginLeft: -29,
        borderLeftWidth: 1,
        borderBottomWidth: 1,
        borderBottomLeftRadius: 25,
        width: 70,
        height: 40,
        top: -15,
        borderBottomColor: colors.timeline,
        borderLeftColor: colors.timeline,
        zIndex: 3,
    },
});

export default styles;
